### ISSUE TITLE
Agree on a coding style

### ISSUE THREAD

**Issue by tomekwi** [tomekwi/mithril-n#5]
Across my recent projects I use the operator-first style. It's actually the philosophy of comma-first, pushed forward to other operators.

It may look strange at first – but if you're interested, [here](http://ajaxian.com/archives/is-there-something-to-the-crazy-comma-first-style)'s some reasoning behind it. As well as that:
- you get clean diffs – only one line changed when you add/remove a value to a JSON/JS file;
- any operator is visible and understandable at the first glance – in western cultures we scan everything from left to right;
- I personally like how you get the left edge aligned like bullets in a list – where every bullet carries a meaning.

Comments? Ideas?

**Comment by tomek-he-him** [comment]
Thanks for your feedback @barneycarroll. I think we haven't fully understood each other – but I did understand you well once I looked at your code sample.

So here's how I'd format it:

``` js
function buttonList (...buttons) { return (                                //  1
    m                                                                      //  2
    ( 'ul'
    ,   gaps
        ( buttons.map(buttons, function buttonView (button) { return (
            m
            ( 'button.btn.btn-default'
            ,   { className: ( button.active()                             //  3
                             ? 'active' 
                             : ''
                             )
                , 'data-active': button.active()
                , onclick: multi                                           //  4
                      ( bm.withAttr('data-active', button.active)
                      , preventDefault
                      )
                }
            , button.label
            )); })                                                         //  5
        )
    )); }
```

1) The main rule of all, and really the only strict one, is **"one idea per line"**. "A function that just returns stuff" is one piece of information (ES6 calls it an arrow function).

2) You're right – it did take me a while to find a neat way to represent Mithril templates in this formatting style. I ended up with one exception for them – that the `m`'s arguments are listed under the `m` itself instead of being indented against it. This way they visually form a sort of tree structure:

``` js
m
( '...'
, ...
, m('...'
    , ...
    )
, mComponent
    ( ...
    )
, m('...'
    , ...
    )
)
```

3) I use a hanging indent where it doesn't seem necessary to break and indent the expression/statement.

4) When a function call's parameters are easier to reason about one at a time, I break and indent the function call as any other expression/statement.

5) These lines must indeed look scaring at first :) But if you scan upwards, you should easily find the line opening the statement – it's the first de-indented one. On our line we must simply close anything the first line has opened. Mithril templates have one extra closing bracket, because of the exception (2).

#### Random thoughts

IMO readability of operator-first formatting really shines with ternary and logical operators. These can get as complex as you like and remain readable:

``` js
if (  isSunday
   || (  isSick
      && !isVerySick
      && hasSickNote
      )
   || isWorkingDay && hasNothingToDo
   ) {
    relax();
    }
```

I also like how you can mix different types of operators, staying within a line limit and keeping your code readable – as the operator is visible on the first glance:

``` js
throw new gutil.PluginError
    ( 'gulp-fancy-plugin-name'
    , "A critical error took place – one that's so complex, that its "
    + "description doesn't fit within an 80-character line limit. Fortunately "
    + "we can span it over multiple lines."
    );
```

#### As for your comments,

> every list item line has to be aware of whether it's got items before it rather than after it.

So basically, an item has to be aware if it's the first one or not. If it's the first one, it gets a `{`, `[` or `(` – otherwise the proper operator. Just like in the real world: when you write a to-do list, you place a comma _before_ writing down a new item _unless it's the first one_.

> It's also somewhat at odds with the principle of not closing statements on the same line that you mention later.

I think you've got me wrong. Do you still think so after seeing my sample?

> In the case of groups of var assignments, I always like to make it explicit and have a separate statement for each.

Me too :) I like to declare all undefined variables in the first statement, and then have one more for each defined one:

``` js
var notReadyYet, toBePopulated;
var valueReady = 'value';
var anotherReadyValue = 'another value';
```

#### So, @barneycarroll,

Let me know if you find this stuff reasonable. I've actually never colaborated on a project in this style, and so never really explained it deeply to anyone yet. I'll be glad to know what you think.

**Comment by barneycarroll** [comment]
> Just like in the real world: when you write a to-do list, you place a comma before writing down a new item unless it's the first one.

In the real world, bullets indicate *every* item. In Javascipt, trailing commas are valid (but IE<9 will throw up on them).

TBH the operator first is more readable overall. In practice I'm happy to go along with all of this :+1:

**Comment by tomek-he-him** [comment]
@barneycarroll since your suggestion in https://github.com/tomekwi/mithril-n/issues/12 I’ve been using airbnb style for all my projects.

But by the way, I’ve just stumbled upon a todoMVC written in [elm](http://elm-lang.org). Nice to see [how good my original style looks](https://github.com/evancz/elm-todomvc/blob/master/Todo.elm#L133) in a pure functional language :) And it looks like they’re using it throughout the community.

Anyway, elm itself is also worth a look. If JavaScript is a language I like, I think I’m falling in love with elm :)

**Comment by barneycarroll** [comment]
Hey @tomekwi, I was just thinking about you the other day — I wrote [a cheeky ultra-minimal function for passing `this` as the first argument of a supplied function](https://www.npmjs.com/package/asarg), and was crestfallen when I realised [_someone_](https://www.npmjs.com/~tomekwi) had already taken `as` on NPM ;)

I've been sticking to my guns on coding style for a while, but TBH I haven't seen fit to cement it. It just happens, but I'm not precious. A new guy came in and started coding in his own particular way. He uses less blank lines, puts semi-colons everywhere, avoids spaces between arguments… it's interesting to have the opportunity to reflect on, but it's certainly not a problem :)

I've seen Elm mentioned before. Looks nice and light, although I don't get the propensity for brackets. What draws you to it?

**Comment by tomek-he-him** [comment]
:) I’m sorry, I really didn’t mean to :)

> I don't get the propensity for brackets

I thought the same when I first saw some Elm code. But – guess what – we were both wrong. The swarms of brackets we see are just lists (`[]`), records (`{}`) or tuples (`()`).

It’s just that they stand out in a peculiar way. And they stand out because there’s virtually no need for grouping things in function calls.

They have some clever tricks for that. What we’d write as `a(b, c, d(e, f))` in JS
would be `a b c (d e f)` in Elm
– or even `a b c <| d e f`
– or even a more natural, bash-like `d e f |> a b c`

> What draws you to it?

Four things, really:
- They seem to have devised a safe type system without sacrificing expressiveness. [These things](https://github.com/evancz/elm-todomvc/blob/bc37c9b97db9e1c1d5db9debf0d900c77461e584/Todo.elm#L32-L37) can be written down optionally – like we write jsDocs – but can just as well be implied by the compiler.
- There are no runtime exceptions, [so they say](http://elm-lang.org/). Whatever could possibly go wrong is caught by the compiler.
- Purity. Functional programming in JS with its `throw`s, `try`s, `process.exit`s, and `element.setAttribute`s is often a struggle.
- This was the biggest wow for me. Their [package system] detects backwards-incompatible [API changes](https://twitter.com/czaplic/status/601826927838650369) and enforces semver.

I don’t have much experience with Elm yet though. It’s not real love yet, just preliminary flirting :)

**Comment by barneycarroll** [comment]
Keep up the flirting! :)

I've come to the end of a year developing with Mithril and I gotta say, I'm looking elsewhere. I used to get some satisfaction helping people get to grips with the API, solve edge cases, and trying to propose changes. But I ended up writing a lot of plugins compensating for deficiencies in the core API and in the end… it just became a quagmire. Now whenever somebody says "I thought I'd be able to do this with Mithril" I just have to walk away because my response is "oh yeah well what you have to understand is [wall of text] so use this plugin because [wall of text]". 

Instead of fighting against the tide with Mithril I'm thinking of bringing my hard-won experience to developing a component & lifestyle framework for citojs, which is an alternative vdom library inspired by Mithril. The reason I bring this up is that citojs deals with document fragments out of the box. Leo says he's doing a re-write of Mithril inspired by citojs's performance, but TBH I'm not sure how much hope I should hold out given the attitude to recurring issues with the fundamental Mithril APIs.

**Comment by tomek-he-him** [comment]
Wow, amazing how similar our paths are :)

I moved away from Mithril even ealier. After quite a successful project where I used Mithril as a framework I realized that I don’t want a framework after all. Everything I made to be reusable turned out to be useless outside the warm embrace of the framework.

So I tried using Mithril as a library – and it occured to me that that it’s not a library at all.

Then I switched to the library **[virtual-dom](https://github.com/Matt-Esch/virtual-dom)** which you surely know. Similar to citojs, so it seems.
